apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "devops-helm.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      {{- include "devops-helm.selectorLabels" . | nindent 6}}
  template:
    metadata:
      labels:
        {{- include "devops-helm.selectorLabels" . | nindent 8}}
    spec:
      containers:
      - image: {{ .Values.image.repository}}:{{ .Values.image.tag}}
        imagePullPolicy: {{ .Values.image.pullPolicy}}
        name: {{ .Values.containers.name}}
        ports:
        - containerPort: {{ .Values.service.targetPort}}      

