apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "devops-helm.labels" . | nindent 4}}
  name: {{ .Values.service.name}}
spec:
  type: {{ .Values.service.type}}
  ports: 
    - name: {{ .Values.service.portName}}
      port: {{ .Values.service.port}}
      targetPort: {{ .Values.service.targetPort}}
  selector:
    {{- include "devops-helm.selectorLabels" . | nindent 4}}


