apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.service.appName}}
  name: {{ .Values.service.name}}
  
spec:
  type: {{ .Values.service.type}}
  selector:
   app: {{- include "devops-helm.selectorLabels" . | nindent 3 }}
  ports: 
    - name: {{ .Values.service.portName}}
      port: {{ .Values.service.port}}
      targetPort: {{ .Values.service.targetPort}}


