apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.service.appName}}
  name: {{ .Values.service.name}}
  
spec:
  type: {{ .Values.service.type}}
  selector:
    {{- include "devops-helm.selectorLabels" . | nindent 4}}
  ports: 
    - name: {{ .Values.service.portName}}
      port: {{ .Values.service.port}}
      targetPort: {{ .Values.service.targetPort}}


