apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "devops-helm.labels" . | nindent 4}}
  name: {{ .Values.service.name}}
spec:
  type: {{ .Values.service.type}}
  ports: 
    - name: {{ .Values.service.portName}}
      port: {{ .Values.service.port}}
      targetPort: {{ .Values.service.targetPort}}
  selector:
    {{- include "devops-helm.selectorLabels" . | nindent 4}}

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
 name: {{ .Values.monitor.name}}
spec:
 selector:
   matchLabels:
    {{- include "devops-helm.labels" . | nindent 4}}
 endpoints:
   - port: {{ .Values.service.portName}}
     path: {{ .Values.monitor.pathendpoint}}