spring:
  application:
    name: devOps-App
  datasource:
    username: obaz-sql
    password: Dreams16
    url: jdbc:postgresql://35.193.98.118/obazdb
    #      url: ${DB_URL:jdbc:postgresql://offorsql.postgres.database.azure.com/primerdb}

    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
#jwt:
#  secret: token_secret
#  expiry: 360000

server:
  port: 8002
  servlet:
    context-path: /